### ISSUE TITLE
IP and time not showing correctly

### ISSUE THREAD

**Issue by sidboy55555** [russellgrapes/telegram-bash-system-monitoring#2] opened 2024-06-05 17:08 UTC
Hi,

First of all, great job on the script!

However, I've encountered an issue where the notifications (to Telegram, terminal log, and the ssh_activity_logins.txt) are displaying the time where the IP address should be, and showing "00:00" where the time should be.

Here's an example of what I'm seeing:

./system-monitoring.sh: line 241: 18:18: syntax error in expression (error token is ":18")
New SSH login: User *[ root ]* from IP *18:18* at 00:00.
./system-monitoring.sh: line 241: 01:00: syntax error in expression (error token is ":00")
New SSH login: User *[ www-data ]* from IP *01:00* at 00:00.
./system-monitoring.sh: line 241: 18:27: syntax error in expression (error token is ":27")
New SSH login: User *[ root ]* from IP *18:27* at 00:00.
./system-monitoring.sh: line 241: 19:02: syntax error in expression (error token is ":02")
New SSH login: User *[ root ]* from IP *19:02* at 00:00.

Additionally, is it possible to log incoming SFTP/rsync connections as well?

EDIT: Forgot to mention I'm using Debian 12.

Thank you!

**Comment by russellgrapes** [comment] 2024-06-20 11:12
Hi, thanks for the feedback! I tested on Debian 12 and was not able to reproduce the issue.

Let's investigate your case further. Could you please provide the output for the following commands on your server:

1. Raw who Output:
`who`
2. Parsing Output:
`who | awk '{print $1, $5, $3, $4}'`
3. Improved Parsing:
`who | awk '{ ip = ($5 ~ /^\(/ ? $5 : "no-ip"); print $1, ip, $3, $4 }' | sed 's/[()]//g'`
4. Locale Settings:
`locale`
5. Shell Version:
`bash --version`
6. Execution Context:
`echo $SHELL`

Please also mention if there are any specific configurations or customizations on your system that might influence the script's behavior. This information will help understand the environment differences and pinpoint the issue more effectively.

**Comment by russellgrapes** [comment] 2024-06-20 18:58
Hi, thanks for your feedback!

I was able to reproduce the issue on the French locale. In version 3.70 of the script, this issue is resolved by forcing _en_US.UTF-8_ for the _who_ command. Enjoy, and thanks for your contribution!

P.S. SFTP support is coming soon. As for monitoring rsync connections, it’s not entirely clear what specific aspects you want to track. Please feel free to open a Discussion to elaborate on this topic.

**Comment by russellgrapes** [comment] 2024-06-21 09:02
I see that `awk` is still extracting the wrong argument from `who` on your system. Could you please provide the output of `who` and `locale` on that system so I can investigate this issue further?

P.s. v3.71 now supports SFTP.

**Comment by russellgrapes** [comment] 2024-06-21 20:08
I made a new fix for locales. Please check v3.74 on your system.

**Comment by sidboy55555** [comment] 2024-06-24 11:43
Hi,

Thanks for the response, I've tested v3.74 and the correct local is printing the output correctly now. And the sftp logs also work great, thnx!

Additionally if two ssh logins are within the same minute, it doesn't log them both, only the first one.
To fix this you could edit the local current_logins under check_ssh_activity to include the pid in the ssh_activity_logins.txt like this.

check_ssh_activity() {
    # Fetch the current SSH sessions
    local current_logins=$(LC_ALL=C who -u | awk '{print $1, $8, $3, $4, $5, $7}') # Extract username, IP, date, time, and pid
    local last_logins=$(cat "$SSH_ACTIVITY_LOGINS" 2>/dev/null)

Further more, I notice only the / disk is being monitored. maybe an option so you can choose which mount points or filesystem under df -h are being monitored?

**Comment by russellgrapes** [comment] 2024-07-16 20:50
Hi, thank you for the feedback! 

Check version 4.00.
It now includes --DISK-TARGET <mount_point>, handle SSH with PID and stores telegram credits in a separate file.

**Closed by russellgrapes** 2024-07-16 20:50 UTC
